# Streamlit Secrets - Para uso no Streamlit Cloud
# IMPORTANTE: Este arquivo NÃO deve ser versionado (incluído no .gitignore)

# MongoDB Connection
MONGO_URI = "mongodb+srv://leonardocampos:leonardocampos@cluster0.7kdvlok.mongodb.net/ToolsConnect?retryWrites=true&w=majority"

# Monday.com API Configuration
[monday]
API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjI2Njg4NzkwNiwiYWFpIjoxMSwidWlkIjoyMzA5NjM0MiwiaWFkIjoiMjAyMy0wNy0wNVQxNDoyNTo1NS4wMDBaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6NDkwNjU3MCwicmduIjoidXNlMSJ9.tRWcVx3Q9oUEPKRMdaEiFzqCf1n0F7NelbjY09jQix4"
BOARD_ID = 926240878
